### ISSUE TITLE
1.19 version needs dependency update (still at 1.18.2 in fabric.mod.json)

### ISSUE THREAD

**Issue by Tursiops-G** [Steveplays28/pathunderfencegates#2]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Path Under Fence Gates' (pathunderfencegates) 1.2 with any version that is compatible with:
		 - minecraft 1.19
Unmet dependency listing:
	 - Mod 'Path Under Fence Gates' (pathunderfencegates) 1.2 requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

---

fabric.mod.json:
  "depends": {
    "fabricloader": ">=0.13.3",
    "minecraft": "1.18.2"

**Comment by James103** [comment]
To update in `fabric.mod.json`:
* Replace `1.18.2` with `1.19` in line 34 (`"minecraft": "1.18.2"`).

Also needs updating in `gradle.properties`:
* Replace `1.18.2` with `1.19` in line 6 (`minecraft_version=1.18.2`).
* Update the value of `yarn_mappings` in line 7 accordingly.

After making these changes, recompile the mod with `gradlew build` (or `./gradlew build`) and test the mod by copying the built jar (without `dev` or `sources`) in `build/libs` to the `mods` folder in a clean 1.19 Fabric instance.

**Comment by Steveplays28** [comment]
I've uploaded a fixed 1.19.x jar to GitHub, Modrinth, and CurseForge (CurseForge is still processing).
