### ISSUE TITLE
Crash when mining hay?

### ISSUE THREAD

**Issue by SKN360** [Steveplays28/pathunderfencegates#9]
I'm working on a modpack and whenever any of my friends mine hay, their entire game crashes. (I even have No More Crashes, which should put them in the title screen instead) The crashlog my friend passed over was this:
```
[00:27:14] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_3614 net.minecraft.class_2680.method_26207()'
    at io.github.steveplays28.pathunderfencegates.util.BlockStateUtil.isBlockAllowedAboveDirtPathBlock(BlockStateUtil.java:13) ~[pathunderfencegates-1.4.0+mc1.19.x.jar:?]
    at net.minecraft.class_2369.handler$eak000$pathunderfencegates$canPlaceAtInject(class_2369.java:520) ~[client-intermediary.jar:?]
    at net.minecraft.class_2369.method_9558(class_2369.java) ~[client-intermediary.jar:?]
    at net.minecraft.class_4970$class_4971.method_26184(class_4970.java:1169) ~[client-intermediary.jar:?]
    at net.minecraft.class_2369.method_9559(class_2369.java:39) ~[client-intermediary.jar:?]
    at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:1149) ~[client-intermediary.jar:?]
    at net.minecraft.class_7165.method_42393(class_7165.java:36) ~[client-intermediary.jar:?]
    at net.minecraft.class_7159$class_7272.method_41707(class_7159.java:143) ~[client-intermediary.jar:?]
    at net.minecraft.class_7159.method_41702(class_7159.java:78) ~[client-intermediary.jar:?]
    at net.minecraft.class_7159.method_41706(class_7159.java:65) ~[client-intermediary.jar:?]
    at net.minecraft.class_7159.method_42392(class_7159.java:32) ~[client-intermediary.jar:?]
    at net.minecraft.class_1937.method_42308(class_1937.java:344) ~[client-intermediary.jar:?]
    at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:1092) ~[client-intermediary.jar:?]
    at net.minecraft.class_1937.method_30092(class_1937.java:256) ~[client-intermediary.jar:?]
    at net.minecraft.class_638.method_30092(class_638.java:157) ~[client-intermediary.jar:?]
    at net.minecraft.class_1937.method_8652(class_1937.java:213) ~[client-intermediary.jar:?]
    at net.minecraft.class_636.method_2899(class_636.java:130) ~[client-intermediary.jar:?]
    at net.minecraft.class_636.method_41932(class_636.java:259) ~[client-intermediary.jar:?]
    at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
    at net.minecraft.class_636.method_2902(class_636.java:258) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1590(class_310.java:1693) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1508(class_310.java:2063) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.14.22.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]```

I'm not sure if it's caused by your mod or not, but it does mention it at the beginning. I'm not too familiar with reading chatlogs either. I could provide the modpack in a .mrpack file (modrinth) if needed. until then, I will have it disabled from now on.

**Comment by Steveplays28** [comment]
Can you send your modlist? Also try removing all other mods and see if the issue remains.

**Comment by Fyoncle** [comment]
I use 1.20.1 Fabric and it doesnt happen on me.
